### ISSUE TITLE
Research character encoding

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#16]
Look up the following terms:
- ASCII
- Unicode 
- UTF-8
- UTF-16

When you are done, create a wiki page called "Character Encoding". Summarize what you have learned. You should be able to get a few paragraphs at least.

**Comment by Prince-linux** [comment]
I just read through and had a fair idea but will still read further on these topics. It isn't that easy though but I am still reading further. I have summarized a bit of what i got.
