### ISSUE TITLE
for-seq-test: program does not follow specification

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#18]
The program should count down by 10s from 50 to -50. However it counts up by 10s from -50 to 50.

This is a bug, so you might want to label it with a bug label.

**Comment by Prince-linux** [comment]
I did it as you specified but it didn't run. so I had to do it this way. If it can wok as you specified, can you please show me?

**Comment by lcabrini** [comment]
Remember that the order of arguments to seq with three arguments is FIRST INCREMENT LAST (from the seq man page). So to get from 50 to -50 you need to have a negative INCREMENT (aka a DECREMENT). Try that.

**Comment by lcabrini** [comment]
If you do something and it doesn't work, then you have to comment. You cannot decide to change the specification. Imagine if you were developing a control system for an airplane and you just changed the spec. It could be very dangerous. So you must not say "I couldn't do X so I did Y instead".

**Comment by retornam** [comment]
@lcabrini  sorry to hijack this ticket, it's been a while we need to catch up. Are you still on irc?

**Comment by lcabrini** [comment]
@retornam been a while since i last irced. but over the weekend I'll log in promise.
