### ISSUE TITLE
Discover the $USER special variable

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#23]
Try this out:

```
echo $USER
```

What output do you get? Try changing user to root by issuing su, followed by the root password. Type the command above again. Did the output change?

You can utilize this to check which user you are logged in as before performing actions. Here is an example:

```
if [[ $USER == 'root' ]]; then
    echo You are like a God on this system
else
    echo You are just a regular user
fi
```

Using this concept, write a mkdir3.sh program and place it in your scripts folder. Let it first check if you are root. If you are not, the program print a messge that "only root can run this program". Otherwise, it should go ahead and ask for the name of the folder and create it, like in mkdir2.sh.

**Comment by Prince-linux** [comment]
echo $USER printed out the user name Prince. when I changed user to root by issuing the su command and typing the root password, the output changed to root.
