### ISSUE TITLE
Discover the $? special variable

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#24]
Try the following sequence:

```
$ ls
$ echo $?
$ zxvrft
$ echo $?
$ ls /doesnotexist
$ echo $?
$ mkdir /foo
$ echo $?
$ echo hello
$ echo $?
$ ping 127.0.0.1
$ echo $?
$ ping foo.bar.bim
$ echo $?
```

Pay careful attention to the value of the output of echo $? in each case. On the Shell Variables wiki page (create it if you have to), create a heading called return value and document your findings.

**Comment by Prince-linux** [comment]
I wrote a wiki page for reference.
