### ISSUE TITLE
Get to know the head and tail commands

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#27]
Linux has two commands called head and tail. To test them out, try these commands.

```
$ head -n 5 /etc/passwd
$ tail -n 3 /etc/passwd
$ dmesg | tail -n 10
$ cat /usr/share/dict/words | head -n 100 | tail -n 10
$ cat /etc/passwd | grep bash | tail -n 1
$ ls | tail -n 2
$ ls ~ | grep D | head -n 1
$ /sbin/ifconfig | grep '^[a-z] | tail -n 2
$ dmesg | grep Bluetooth | head -n 5
$ cat /usr/share/dict/words | grep ing | head -n 100 > ~/some-words.txt
$ cat /usr/share/dict/words | head -n 100 | grep ing > ~/other-words.txt
```

Create a wiki page called Heads and Tails, and describe what the commands head and tail do. Then go through each of the commands above and show their output as well as explain why you get that output.

If you have problems with understanding the pipeline commands, break them down. For instance you  could do something like this:

```
$ cat /usr/share/dict/words
$ cat /usr/share/dict/words | head -n 100
$ cat /usr/share/dict/words | head -n 100 | tail -n 10
```

At each stage, check the output and understand why you get that output. Also keep in mind that pipelines are always exectued from the left to the right.

In the last two examples, would you expect to get the same results or different ones? Why? Explain this clearly on the wiki page.

**Comment by Prince-linux** [comment]
had a problem with the 8th one that's /sbin/ifconfig | grep '^[a-z] | tail -n 2. with the grep command is it grep ^[a-z] or grep '^[a-z]. cos the one you gave me gave me this output > and nothing else but with the one i am suggesting gave me this 
lo        Link encap:Local Loopback  
ppp0      Link encap:Point-to-Point Protocol .
so which is which pls?
