### ISSUE TITLE
Create script sort-numbers.sh

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#28]
Write a script called sort-numbers.sh. This should first ask the user to input 10 numbers. Each number should be added to a file called unsorted.txt. Finally the program should print out the sorted list of numbers.

Make sure you are getting the list properly sorted. If it is not, check the man page for the sort command to see if you need to pass any options to the sort command.

**Comment by Prince-linux** [comment]
I am having a problem with getting the output of all ten input to unsorted.txt
can you please help?
