### ISSUE TITLE
create a wiki page entitled Open Source

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#29]
On this page give a summary about what open source is. Look up the OSI definition and summarize what is required for a software to be considered open source.

Add a section that compares and contrasts the concepts "open source" and "free software". Is there any difference between these two concepts or are they the same? What about philosophically? 

Add a section that discusses different open source licenses. Especially discuss the difference between GPL style licenses and BSD style licenses.

Add a section where you list a few open source projects. You should add at least 10.

**Comment by Prince-linux** [comment]
Done
