### ISSUE TITLE
Get to know gcc

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#30]
The C compiler, cc, is considered a fundamental part of the system. On Linux systems, which use tools from the GNU project, cc is called gcc, although you should also be able to call it as cc.

There is a nasty tendency of some Linux distributions not to include the C compiler in the default install these days. I consider this blasphemy. I Unix system without a C compiler is like a person without a head.

First, let's make sure that gcc is installed:

```
$ gcc
```

If you get

```
bash: gcc: command not found
```

Then you are going to have to install the C compiler. But if you get this.

```
gcc: fatal error: no input files
compilation failed
```

Then gcc is installed.

If gcc is not installed, then follow this procedure to install it. However, if it is already installed, close this issue manually.

To execute the following, you are going to need to be connected to the Internet. I use $ to indicate normal user prompt, and # to indicate root prompt. This is standard in the Unix community.

```
$ su
<type root password>
# apt-get update
# apt-get install build-essential
# exit
$ gcc
```

If everything has gone well, you should get a message indicating that compilation failed. Then you are ok.

The package build-essential is a so called meta-package that depends on gcc as well as some other fundamental tools for building software on a Linux system.

**Comment by Prince-linux** [comment]
It was already installed please.
