### ISSUE TITLE
Getting to know ownership and file permissions

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#31]
It is time to learn about file ownership and permissions. Try this (as a normal user):

```
$ cat /var/log/messages
```

The file /var/log/messages is an important log file. On debian systems, normal users don't have access to log files. But who does? We can find out by issuing:

```
$ ls -lh /var/log/messages 
-rw-r----- 1 root adm 17M lug  8 17:27 /var/log/messages
```

This tells us quite a bit about the file /var/log/messages. First of all to the far right you see the name of the file. Then you will have the modification date/time before that. Still before you can see that the file is 17Mb large (your number may be different. This is on my system.

Then it gets interesting. The part that says **root** followed by **adm** refers to the user and the group that owns the file. All file system objects in Unix/Linux are owned by a user and a group. This particular file is owned by the user root (the system admin) and the group adm (a group for users with admin privileges). 

But what can root and adm do with the file? That is where the last bit comes in. Imagine ten dashes in succession. Like so:

```
----------
```

The first one determines the type of object this is. For a regular file, the value is just a dash -. For a directory, you would see a d there instead. You will see other file system objects later.

Then comes three groups of three dashes. These three are
1. Owner permissions
2. Group permissions
3. World permissions (that is all other users)

Each of these has three available permissions:
1. Read permission
2. Write permission
3. Execute permission

So if we look at the permissions of /var/log/messages, we see this

```
-rw-r-----
```

Removing the first dash and separating the three permissions we get this

| Owner Permissions | Group Permissions | World Permissions |
| --- | --- | --- |
| rw | r | none |

So the owner (root) can read from and write to the file, the group (adm) can read the file but not write to it. All other users cannot access the file at all.

Create a wiki page and list the file system object type, the owner, group and permissions of each of the following files (if they exist)
1. $HOME (use ls /home and check the permissions of your own folder)
2. /etc/passwd
3. /etc/shadow
4. /var/spool/mail
5. /bin/ls
6. /boot/vmlinuz-\* (Your version of the kernel may differ from mine. If you have multiple installed, just choose one)
7. /dev/sda
8. /dev/null
9. /sys/kernel/notes
10. /var/cache/apt/pkgcache.bin

Put the results on a wiki page called "File System Permissions" and insert the results in a table with the format. I added one entry to show you how to fill out the table. You can read up on github markdown to learn how to create a table.

| Name | Type | Owner | Group | Owner Perms | Group Perms | World Perms |
| --- | --- | --- | --- | --- | --- | --- |
| /var/log/messages | file | root | adm | read, write | read | none |

If you come across a file type other than - or d, here are a few others:
1. l  means symbolic link
2. c means character device
3. b means block device

If you see any others, just type the letter in the Type field. We will learn more about the various types as we go on.

**Comment by lcabrini** [comment]
Here is a page that shows you how to use markdown: https://guides.github.com/features/mastering-markdown/

**Comment by Prince-linux** [comment]
I am done.
