### ISSUE TITLE
Write a wiki page on Linux distros

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#33]
Write a wiki page where you explain what a distro is. Also include information on the following distros:
1. Red Hat Linux
2. SuSE Linux
3. Debian GNU/Linux
4. Ubuntu
5. Gentoo Linux
6. SystemRescueCD
7. Damn Small Linux
8. Vyatta
9. Fedora Core
10. PC Linux OS

**Comment by Prince-linux** [comment]
Done please
