### ISSUE TITLE
Virtual Linux Machines: include sections on each machine

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#34]
Add a section for each machine to the wiki page. Include output from the following commands:
1. hostname
2. df -h
3. /sbin/ifconfig eth0
4. uname -a

**Comment by lcabrini** [comment]
Actually, for the hostname command, use the --fqdn option

```
$ hostname --fqdn
```

**Comment by Prince-linux** [comment]
Done pls
