### ISSUE TITLE
Find out if your systems are running an SSH server

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#38]
Use the apt-cache command to find out if the SSH server is installed on your machines. 

```
$ apt-cache show openssh-server
```

The output is probably going to be quite long so you may want to pipe the output to the less pager.

```
$ apt-cache show openssh-server | less
```

When in pager mode, you can use the up/down keys to scroll through the text. Use 'q' to quit back to the terminal.

Look through the output to find out if the package is installed or not. Do this on the host and both your virtual machines. If it is installed, just document everything on a wiki page called SSH, in a section called SSH Server.

If the package is not installed on any machine, install it by becoming root and then invoking

```
# apt-get install openssh-server
```

Once installed, confirm that the ssh server (sshd) is running, by invoking

```
$ pgrep sshd
```

Once installed on all machines, list down the version of openssh that is installed on each machine on the SSH wiki page.

**Comment by Prince-linux** [comment]
It was installed on all machines
I wanted to install on the virtual machines but had problems with managing package because the default mirror is the CD
