### ISSUE TITLE
Create a wiki page called "Basic Linux Commands"

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#4]
Create a new page on the wiki and call it "Basic Linux Commands". Add a few commands that you have learned so far, and a short description to each.

**Comment by lcabrini** [comment]
By the way, notice that in this case you cannot auto-close this issue with a commit message. So when you are done, you will have to manually close this issue.

**Comment by Prince-linux** [comment]
how do I close issue #4 Pls??

**Comment by Prince-linux** [comment]
manually to be precise

**Comment by lcabrini** [comment]
On the issue page (this page), click on the "Close issue" button at the bottom.

**Comment by Prince-linux** [comment]
oh okay. thanx
