### ISSUE TITLE
Discover the /etc/fstab file

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#41]
The file /etc/fstab contains static file system information. You can get information about this file by invoking:

```
$ man fstab
```

Use the man page to describe the entries in your own /etc/fstab file. Also compare the output of the mount command which, if called without options, will show a list of all mounted file systems.

```
$ mount
```

Create a wiki page called System configuration. On this page, create a section called /etc/fstab and explain the contents of your fstab.

**Comment by lcabrini** [comment]
As mentioned over phone, remember to use

```
$ cat /etc/fstab
```

as this file is a text file with configuration information.

**Comment by Prince-linux** [comment]
I am done please
