### ISSUE TITLE
Compare compression tools

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#42]
You are going to run an experiment to compare different compression tools. 
## Preparation
1. read up on compression (not in detail but just to get an overview): https://en.wikipedia.org/wiki/Data_compression
2. Acquire resource files: you will need the resource files listed in the next section
3. Prepare wiki page: Compression
## Resource files

Create a folder, you could call it compression. Do **NOT** put it in your github directory, because some of the files may be very big and we don't want to waste space on github with them. In the folder you need to put one file of each of the following file types:
1. Text document (you can use /usr/share/common-licenses/GPL-3, simply copy this file into the folder you just created.
2. JPEG image (you could download one from the Internet)
3. PNG image (you could download one from the Internet)
4. OpenOffice/LibreOffice document. You could just open the OO/LO word processor and type a few senctences and save the file into the folder
5. FLV video: many people have these. You could also use a tool like youtube-dl or other download tool for youtube videos to download one from youtube.
6. AVI video: these are often big, but many people have movies. Ask if you can copy a movie from somebody. Worst case, if you can come over, I have several, but you would need to bring a pen drive
7. MP3 or OGG audio file. Could be a song, or a audiobook or something like that.
8. A linux executable. You could copy one from /usr/bin, with cp /usr/bin/vim-basic ~/compression, for instance
9. An SVG image. You should be able to find these online. If you have inkscape installed, you could also create your own.
10. A PDF document. You can get several online, if you don't already have some.
## The tools

You are going to compare the following compressions tools which are all common on Linux systems.
1. gzip
2. bzip2
3. xz

You will probably have them all installed, but in case any of them (xz is newer and may not be installed by default on older debian systems), you can do the following as root:

```
# apt-get install xz-utils bzip2 gzip
```

In short once you are done you should have access to all the following tools:
1. gzip
2. gunzip
3. bzip2
4. bunzip2
5. xz
6. unxz

You could try typing these in the terminal just to see that they are there. Each of the commands supports a --version option. So run each with this option (gzip --version, bzip2 --version and xz --version) and take note of the version numbers. Write these down on the wiki page in a section called Compression tools.

The gzip tool compresses a file, gunzip uncompresses it. Same with bzip2/bunzip2 and xz/unxz. Each has their manual page that you can refer to. 
## The experiment

Create a table with the following headings: file name, original size, gzip size, gzip %, gzip/gunzip time, bzip2 size, bzip2 %, bzip2/bunzip2 time, xz size, xz %, xz/unxz time. For each of the files first take not of the original file size (ls -l will give you this). Then compress the files, with each of the tools and take note of the size of the compressed file, as well as by how much the file size was compressed (compressed size / uncompressed size \* 100). Repeat this for all files, using each compression tool and fill out the table.

(Beware that some files may take quite a while to compress, especially with bzip2. Just be patient).
## Benchmarking

You will have noticed the headings gzip/gunzip time, bzip2/bunzip time and xz/unxz time. This are meant to store how long it takes to compress each file. The way you will get this information that instead of typing:

```
$ gzip zebra.jpg
```

you will intead type 

```
$ time gzip zebra.jpg
```

Same when you uncompress. do this:

```
$ time gunzip zebra.jpg.gz
```

And take not of the time, putting it in the appropriate column. If the file zebra.jpg (never mind the name, I have a picture like that on my system) took 0.5s to compress with gzip and 0.7s to uncompress, then in the gzip/gunzip time column for that file you put in:

```
0.5s / 0.7s
```

Do this for every file.
## Conclusions

Add a section at the bottom of the wiki page called Summary. Here study the date in the table and try to draw conclusions based on your results. Also create another section called Usage where you try to summarize the main reasons why one would like to compress files.

**Comment by Prince-linux** [comment]
Having Problem with how to get percentage of the compression tools I used. Kindly help out.

**Comment by Prince-linux** [comment]
Hello I have searched online for how to get the percentage and didn't get anything the closest I got was this but it is in .tar format 

% SIZE=`du -sk folder-with-big-files | cut -f 1`
And then:

% tar cvf - folder-with-big-files | pv -p -s ${SIZE}k | \ 
     bzip2 -c > big-files.tar.bz2
