### ISSUE TITLE
write a script that prints the names of the weekdays

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#5]
Call the program weekdays. Place it in the scripts folder. Run it a few times an notice that each time the output is exactly the same. Draw conclusions about the order in which statements in a script are executed.

**Comment by Prince-linux** [comment]
I couldn't run the program. I only did the cat command 
but I didnt know how to run the script. Please show me how to

**Comment by lcabrini** [comment]
Just do 

```
bash weekdays.sh
```

The program looks ok.
