### ISSUE TITLE
write a script that creates folders

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#6]
Write a script that creates the following folder structure:

```
2010
    - accounts
    - hr
    - sales
2011
    - accounts
    - hr
    - sales
2012
    - accounts
    - hr
    - sales
2013
    - accounts
    - hr
    - sales
2014
    - accounts
    - hr
    - sales
2015
    - accounts
    - hr
    - sales
```

That is the years, should be folders, and for each year, accounts, hr and sales should be subfolders.

**Comment by Prince-linux** [comment]
hello lorenzo
my program is not working oo
I decided to run it but it isnt working

**Comment by lcabrini** [comment]
ok, can you make a commit? just don't add closes #6. instead put refs #6

**Comment by Prince-linux** [comment]
sorry I closed it
but please run it and see if it works and if it doesn't i will need corrections

**Comment by lcabrini** [comment]
It looks fine.
