### ISSUE TITLE
Try out the ping command

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/prince-linux-learning#8]
Try out the ping command on Linux. Try the following

```
ping -c 5 localhost
ping -c 3 127.0.0.1
ping -c 10 google.com
ping -c 5 gnome.org
ping -c 4 192.168.15.4
```

Which ones require you to be online before they work. Which ones always work? Which ones never work? Based on the output you get, what do you think the -c command-line option to ping means.

**Comment by Prince-linux** [comment]
the -c command-line option to the ping means to wait until a number of counts is expired after sending and requesting of packet data and stops count.
 ping -c 5 localhost and ping -c 3 127.0.0.1 always works
ping -c 10 google.com and ping -c 5 gnome.org never works but it did work when I was online.
pinc -c 4 192.168.15.4 requires me to be online and also not reachable when offline.
